[pytest]
testpaths = tests

python_functions = test_

python_files = [a-zA-Z]*.py

python_classes = test_

filterwarnings = 
    ignore::DeprecationWarning
    ignore::FutureWarning

log_cli = True
log_cli_level = INFO